<!--NAVIGATION-->
< [Álgebra Lineal Numérica](Prac_AlgebraMatricialNumerica.ipynb) | [Planteamiento del problema y motivación](Planteamiento-del-problema-Motivacion.ipynb)| [Método de las potencias](Metodo-Potencias.ipynb) | [Ejercicios](Ejercicios.ipynb) >

*Este cuaderno contiene un extracto traducido y adaptado al español por [Pedro González Rodelas](https://www.ugr.es/~prodelas/) de un capítulo del libro [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), cuyo contenido (en su versión original en inglés) también está disponible online en el siguiente link [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*El copyright del libro pertenece a Elsevier, pero también se encuentra disponible online la versión interactiva del mismo para una mejor experiencia de aprendizaje. Todos los códigos se publican bajo la licencia [MIT](https://opensource.org/licenses/MIT). Así pues, si encuentra útil este contenido, puede considerar la posibilidad de apoyar este trabajo a través de [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) o bien [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Valores y Vectores Propios con Python

Aunque los métodos que introdujimos hasta ahora parecen complicados, el cálculo efectivo de los valores y los vectores propios en Python es bastante fácil. La principal función incorporada en Python para resolver el problema de valores/vectores propios para una matriz cuadrada es la función `eig` en `numpy.linalg`. Veamos cómo podemos usarla. 

**EJEMPLO:** Calcule los valores y vectores propiios de la matriz $A = \begin{bmatrix}
0 & 2\\
2 & 3\\
\end{bmatrix}$. 

In [2]:
import numpy as np
from numpy.linalg import eig

In [37]:
?eig

In [55]:
A = np.array([[0, 2], 
              [2, 3]])
λs,V=eig(A)
print('valores propios: ', λs)
print('vectores propios asociados: ', V)

valores propios:  [-1.  4.]
vectores propios asociados:  [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [56]:
# comprobaciones
i = 1;
np.dot(A,V[:,i]) - λs[i]*V[:,i]

array([0., 0.])

In [57]:
V

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [58]:
i = 0
V[:,i]

array([-0.89442719,  0.4472136 ])

**EJEMPLO** Calcule ahora los valores y vectores propios de la matriz 3$\times$3, 

$A = \begin{bmatrix}
2 & 2 & 4\\
1 & 3 & 5\\
2 & 3 & 4\\
\end{bmatrix}$.

In [59]:
A = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
λs,V=eig(A)
print('valores propios: ', λs)
print('vectores propios asociados: ', V)

valores propios:  [ 8.80916362  0.92620912 -0.73537273]
vectores propios asociados:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [60]:
# comprobaciones
i = 0;
np.dot(A,V[:,i]) - λs[i]*V[:,i]

array([3.55271368e-15, 0.00000000e+00, 1.77635684e-15])

<!--NAVIGATION-->
< [Álgebra Lineal Numérica](Prac_AlgebraMatricialNumerica.ipynb) | [Planteamiento del problema y motivación](Planteamiento-del-problema-Motivacion.ipynb)| [Método de las potencias](Metodo-Potencias.ipynb) | [Ejercicios](Ejercicios.ipynb) >